import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Globe2, GraduationCap, HandHeart, Languages, Sparkles } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { CourseCard } from "@/components/course-card";
import { ButtonLink, SectionTitle } from "@/components/ui";
import { useContent } from "@/lib/content-store";

export const Route = createFileRoute("/")({ head:()=>({meta:[{title:"Créateur Centre Monastir — Le partenaire de votre réussite"},{name:"description",content:"Formations en langues, compétences professionnelles et accompagnement vers l'Allemagne à Monastir."},{property:"og:title",content:"Créateur Centre Monastir"},{property:"og:description",content:"Le partenaire de votre réussite."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: Home });
function Home(){const {data}=useContent();const active=data.courses.filter(c=>c.status==="active");const languageCourses=active.filter(c=>c.categorySlug==="langues");return <SiteShell>
 <section className="relative overflow-hidden bg-secondary py-20 text-secondary-foreground md:py-28"><div className="absolute inset-y-0 right-0 hidden w-[38%] border-l border-secondary-foreground/10 lg:block"><div className="grid h-full grid-cols-3 opacity-20">{[...Array(9)].map((_,i)=><div key={i} className="border-b border-r border-secondary-foreground/30"/>)}</div></div><div className="container-shell relative grid items-center gap-12 lg:grid-cols-[1.3fr_.7fr]"><div><p className="eyebrow text-accent">{data.homepage.heroSubtitle}</p><h1 className="max-w-4xl">{data.homepage.heroTitle}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-secondary-foreground/70">{data.homepage.heroDescription}</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink to="/languages">Découvrir nos formations</ButtonLink><ButtonLink to="/contact" variant="light">Nous contacter</ButtonLink></div></div><div className="hidden lg:grid lg:justify-end"><div className="grid size-72 place-items-center border border-accent/40 p-8"><Globe2 className="size-24 text-accent"/><p className="text-center font-display text-2xl">Langues · Métiers<br/>Allemagne</p></div></div></div></section>
 <section className="py-20"><div className="container-shell"><SectionTitle eyebrow="Langues" title="Parlez la langue de vos ambitions" text="Des parcours progressifs, pratiques et adaptés à votre objectif."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{languageCourses.map((c,i)=><Link key={c.id} to="/courses/$id" params={{id:c.id}} className="group flex items-center justify-between border-b border-border py-5 text-xl font-bold hover:text-primary"><span className="flex items-center gap-4"><span className="text-sm text-muted-foreground">0{i+1}</span>{c.title}</span><ArrowRight className="size-5 transition-transform group-hover:translate-x-1"/></Link>)}</div><div className="mt-10"><ButtonLink to="/languages" variant="secondary">Voir les formations en langues</ButtonLink></div></div></section>
 <section className="bg-muted py-20"><div className="container-shell grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Projet Allemagne</p><h2>{data.homepage.germanyTitle}</h2><p className="lead mt-5">{data.homepage.germanyText}</p><div className="mt-8"><ButtonLink to="/germany">Découvrir les opportunités</ButtonLink></div></div><div className="grid gap-3 sm:grid-cols-2">{["Apprentissage de l'allemand","Préparation du dossier","Formation et emploi","Accompagnement administratif"].map((x,i)=><div className="card p-5" key={x}><span className="mb-8 grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><Check className="size-4"/></span><p className="font-bold">{x}</p><p className="mt-1 text-xs text-muted-foreground">Étape {i+1}</p></div>)}</div></div></section>
 <section className="py-20"><div className="container-shell"><SectionTitle eyebrow="Savoir-faire" title="Des formations pratiques" text="Apprenez une technique concrète et développez votre créativité."/><div className="grid gap-5 md:grid-cols-3">{active.filter(c=>c.categorySlug==="formation-professionnelle").map(c=><CourseCard key={c.id} course={c}/>)}</div><div className="mt-10"><ButtonLink to="/professional-training" variant="secondary">Voir les formations professionnelles</ButtonLink></div></div></section>
 <section className="border-y border-border py-20"><div className="container-shell"><SectionTitle eyebrow="Notre méthode" title="Pourquoi choisir CMM"/><div className="grid gap-8 md:grid-cols-4">{([[HandHeart,"Accompagnement personnalisé"],[Sparkles,"Méthodes modernes et pratiques"],[GraduationCap,"Préparation aux examens"],[Languages,"Projets en Allemagne"]] as const).map(([Icon,text])=><div key={String(text)}><Icon className="mb-5 size-7 text-primary"/><h3 className="font-sans text-base">{String(text)}</h3></div>)}</div></div></section>
 <section className="py-20"><div className="container-shell"><SectionTitle eyebrow="Témoignages" title="Ce que pensent nos étudiants" text={data.testimonials.some(t=>t.published)?"":"Les témoignages seront affichés après validation des autorisations."}/>{data.testimonials.filter(t=>t.published).length>0&&<div className="grid gap-5 md:grid-cols-2">{data.testimonials.filter(t=>t.published).map(t=><blockquote className="card p-7" key={t.id}><p className="text-lg leading-8">“{t.quote}”</p><footer className="mt-5 flex items-center gap-3 text-sm font-bold">{t.photo&&<img src={t.photo} alt={t.name} className="size-10 rounded-full border border-border object-cover"/>}{t.name}</footer></blockquote>)}</div>}</div></section>
 <section className="bg-primary py-16 text-primary-foreground"><div className="container-shell flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><h2>{data.homepage.ctaTitle}</h2><p className="mt-2 opacity-80">{data.homepage.ctaText}</p></div><div className="flex flex-wrap gap-3"><ButtonLink to="/register" variant="light">S'inscrire</ButtonLink><Link to="/contact" className="rounded-md border border-primary-foreground/40 px-5 py-3 text-sm font-bold">Nous contacter</Link></div></div></section>
 </SiteShell>}