/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GermanyRouteImport } from './routes/germany'
import { Route as GermanyWorkRouteImport } from './routes/germany-work'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfessionalTrainingRouteImport } from './routes/professional-training'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminGermanyRouteImport } from './routes/admin/germany'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GermanyRoute = GermanyRouteImport.update({
  id: '/germany',
  path: '/germany',
  getParentRoute: () => rootRouteImport,
} as any)
const GermanyWorkRoute = GermanyWorkRouteImport.update({
  id: '/germany-work',
  path: '/germany-work',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalTrainingRoute = ProfessionalTrainingRouteImport.update({
  id: '/professional-training',
  path: '/professional-training',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGermanyRoute = AdminGermanyRouteImport.update({
  id: '/germany',
  path: '/germany',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/germany': typeof GermanyRoute
  '/germany-work': typeof GermanyWorkRoute
  '/languages': typeof LanguagesRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/professional-training': typeof ProfessionalTrainingRoute
  '/register': typeof RegisterRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/germany': typeof AdminGermanyRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/germany': typeof GermanyRoute
  '/germany-work': typeof GermanyWorkRoute
  '/languages': typeof LanguagesRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/professional-training': typeof ProfessionalTrainingRoute
  '/register': typeof RegisterRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/germany': typeof AdminGermanyRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/germany': typeof GermanyRoute
  '/germany-work': typeof GermanyWorkRoute
  '/languages': typeof LanguagesRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/professional-training': typeof ProfessionalTrainingRoute
  '/register': typeof RegisterRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/germany': typeof AdminGermanyRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/germany'
    | '/germany-work'
    | '/languages'
    | '/legal'
    | '/privacy'
    | '/professional-training'
    | '/register'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/germany'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/courses/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/germany'
    | '/germany-work'
    | '/languages'
    | '/legal'
    | '/privacy'
    | '/professional-training'
    | '/register'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/germany'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/courses/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/contact'
    | '/germany'
    | '/germany-work'
    | '/languages'
    | '/legal'
    | '/privacy'
    | '/professional-training'
    | '/register'
    | '/admin/categories'
    | '/admin/courses'
    | '/admin/germany'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/courses/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GermanyRoute: typeof GermanyRoute
  GermanyWorkRoute: typeof GermanyWorkRoute
  LanguagesRoute: typeof LanguagesRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalTrainingRoute: typeof ProfessionalTrainingRoute
  RegisterRoute: typeof RegisterRoute
  CoursesIdRoute: typeof CoursesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/germany': {
      id: '/germany'
      path: '/germany'
      fullPath: '/germany'
      preLoaderRoute: typeof GermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/germany-work': {
      id: '/germany-work'
      path: '/germany-work'
      fullPath: '/germany-work'
      preLoaderRoute: typeof GermanyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-training': {
      id: '/professional-training'
      path: '/professional-training'
      fullPath: '/professional-training'
      preLoaderRoute: typeof ProfessionalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/germany': {
      id: '/admin/germany'
      path: '/germany'
      fullPath: '/admin/germany'
      preLoaderRoute: typeof AdminGermanyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminGermanyRoute: typeof AdminGermanyRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminGermanyRoute: AdminGermanyRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GermanyRoute: GermanyRoute,
  GermanyWorkRoute: GermanyWorkRoute,
  LanguagesRoute: LanguagesRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalTrainingRoute: ProfessionalTrainingRoute,
  RegisterRoute: RegisterRoute,
  CoursesIdRoute: CoursesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
